### ISSUE TITLE
Interest rate shown is wrong by factor 100

### ISSUE THREAD

**Issue by andreas-h** [peti/hledger-interest#2]
With hledger-interest version 1.4.4 (on Debian Stretch), a call of

    $ hledger-interest -f myloan.ledger --30E-360isda --annual=0.10 --today -s Einnahmen:Zinsen -t Aktiva:Darlehen Aktiva:Darlehen

leads to the output

    2016/11/17 0.10% interest for € 7340 over 317 days
        Aktiva:Darlehen         € 646
        Einnahmen:Zinsen              € -646

I believe the string describing the interest positions should read `10.00%` instead of `0.10%`.

**Comment by peti** [comment]
Nice catch, thank you very much for the report. I've released http://hackage.haskell.org/package/hledger-interest-1.5.1, which contains a fix.
