### ISSUE TITLE
Question on usage

### ISSUE THREAD

**Issue by schoettl** [peti/hledger-interest#4]
Hi, cool and essential add-on for hledger! I just don't understand how I could use it in a practical application:

In my understanding, at the end of the year, I would use `hledeger interest` to rewrite the journal like:

```
hledger-interest -f my.journal [...] > tmp && mv tmp my.journal
```
(with git version control, of course)

But when I do the same thing at the end of the next year, hledger-interest duplicates the interest book entries of the first year.

How can I avoid or handle this? Thank you!

**Comment by peti** [comment]
I typically use `hleder-interest` such that I have a trivial file `main.ledger`, which simply includes two (or more) other files:

~~~
include interest.ledger
include foobar.ledger
~~~

`foobar.ledger` contains the manually edited data and `interest.ledger` is generated from `foobar.ledger` with `hledger-interest` by a simple `Makefile`. So, basically, I edit `foobar.ledger`, call `make` to update `interest.ledger`, and then direct all my use of `hledger`, `hledger-ui` or `hledger-web` at `main.ledger` to make sure the tools see both data sets.

Does this make sense?

**Comment by schoettl** [comment]
Oh, alright, that is clever. A just want to add that `-q`, `--quiet` must be passed to `hledger-interest` in this scenario.

I add a `Makefile` example for completeness:

```
interest.ledger: foobar.ledger
    hledger-interest -f main.ledger --quiet --act --annual=0.05 -s Expenses:Interest -t Liabilities:Loan Liabilities:Loan > $@
```

(based on examples in the repo README)
