### ISSUE TITLE
Cannot build v1.6.1 because failed to build hledger-lib-1.21

### ISSUE THREAD

**Issue by agryaznov** [peti/hledger-interest#9]
Cannot build v1.6.1 because failed to build hledger-lib-1.21 (reported [here](
https://github.com/simonmichael/hledger/issues/1514))

v1.5.5 with hledger-lib-1.81.1 built successfully

**Comment by peti** [comment]
This issue is out of my hands. I think you did the right thing reporting it to the hledger folks. Once hledger-lib is fixed, hledget-interest is probably going to compile fine.
